theme: jekyll-theme-architect

</head>

<body>

  <div id="wrapper">

    <div id="brand">
      <a href="http://paypal.github.io/"><img src="https://paypal.github.io/accessible-html5-video-player/images/PayPalOpenSourcecolor.svg" width="224" height="28" alt="PayPal open source"></a>
    </div>

    <h1><img src="https://paypal.github.io/accessible-html5-video-player/images/logo-accessible-HTML5-video-player.svg" width="30" height="30" alt=""> Accessible Responsive HTML5 Video Player</h1>

    <div class="px-video-container" id="myvid">
      <div class="px-video-img-captions-container">
        <div class="px-video-captions hide"></div>
        <div class="px-video-wrapper">
          <video poster="media/poster_PayPal_Austin2.jpg" class="px-video" controls>
      			<!-- video files -->
      			<source src="https://content.jwplatform.com/videos/GIFBDWWA-LjeTWl7C.mp4" />

      			<!-- text track file -->
      			<track kind="captions" label="English captions" src="media/captions_PayPal_Austin_en.vtt" srclang="en" default />

      			<!-- fallback for browsers that don't support the video element -->
      			<div>
      				<a href="https://www.paypalobjects.com/webstatic/mktg/videos/PayPal_AustinSMB_baseline.mp4">
      					<img src="media/poster_PayPal_Austin2.jpg" width="640" height="360" alt="download video" />
      				</a>
      			</div>
      		</video>
        </div>
      </div>
