theme: jekyll-theme-architect

<video controls="controls">
  <source type="video/mp4" src="https://cdn4.dogeek.net/hls/1793-1514886550/4k/1793-1514886550.m3u8"></source>
  <source type="video/webm" src="filename.webm"></source>
  <p>Your browser does not support the video element.</p>
</video>
